# Generated by Django 4.1.7 on 2023-03-03 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('STAFF', 'Staff'), ('EMPLOYEE', 'Employee')], max_length=50, null=True),
        ),
    ]
