# Generated by Django 3.2 on 2023-03-03 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('users', '0003_remove_user_campany'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='campany',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
    ]
