# Generated by Django 4.1.7 on 2023-03-03 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0002_alter_assets_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetlogs',
            options={'ordering': ['check_out'], 'verbose_name': 'assets_log', 'verbose_name_plural': 'assets_logs'},
        ),
        migrations.RemoveField(
            model_name='assets',
            name='collected_by',
        ),
        migrations.AddField(
            model_name='assetlogs',
            name='collected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
