# Generated by Django 4.1.7 on 2023-03-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_alter_assets_category_alter_assets_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetlogs',
            name='condition',
            field=models.CharField(choices=[('NEW', 'New'), ('FAIRLY_USED', 'Fairly_Used')], default='NEW', max_length=20),
        ),
    ]
