# Generated by Django 4.1.7 on 2023-03-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_alter_assetlogs_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetlogs',
            name='check_out',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
